// app/_data/products.ts
import type { Product } from "../_context/CartContext";

export const products: Product[] = [
    {
        id: 1,
        name: "Classic Vanilla Ice Cream",
        description: "Creamy vanilla ice cream topped with cherry.",
        price: 4.99,
        imageUrl: "/images/brownie.png",
        rating: 4.9,
        category: "Canned Ice Cream",
        available: true,
    },
    {
        id: 2,
        name: "Chocolate Delight Ice Cream",
        description: "Rich chocolate ice cream with fudge swirls.",
        price: 5.29,
        imageUrl: "/images/brownie.png",
        rating: 4.8,
        category: "Canned Ice Cream",
        available: true,
    },
    {
        id: 3,
        name: "Berry Swirl Frozen Yogurt",
        description: "Low-fat yogurt with mixed berry swirl.",
        price: 4.49,
        imageUrl: "/images/brownie.png",
        rating: 4.7,
        category: "Frozen Yogurt",
        available: true,
    },
    {
        id: 4,
        name: "Mango Frozen Yogurt",
        description: "Refreshing mango-flavoured frozen yogurt.",
        price: 4.19,
        imageUrl: "/images/brownie.png",
        rating: 4.6,
        category: "Frozen Yogurt",
        available: true,
    },
    {
        id: 5,
        name: "Strawberry Shortcake",
        description: "Strawberry ice cream layered with shortcake.",
        price: 5.29,
        imageUrl: "/images/brownie.png",
        rating: 4.9,
        category: "Ice Cream Cakes",
        available: true,
    },
    {
        id: 6,
        name: "Chocolate Celebration Cake",
        description: "Chocolate ice cream cake with crunchy base.",
        price: 6.49,
        imageUrl: "/images/brownie.png",
        rating: 4.8,
        category: "Ice Cream Cakes",
        available: true,
    },
    {
        id: 7,
        name: "Oreo Crunch Milkshake",
        description: "Vanilla shake blended with Oreo cookie pieces.",
        price: 3.99,
        imageUrl: "/images/brownie.png",
        rating: 4.7,
        category: "Milkshakes",
        available: true,
    },
    {
        id: 8,
        name: "Strawberry Dream Milkshake",
        description: "Fresh strawberry milkshake topped with cream.",
        price: 3.79,
        imageUrl: "/images/brownie.png",
        rating: 4.6,
        category: "Milkshakes",
        available: true,
    },
    {
        id: 9,
        name: "Mango Twist Popsicle",
        description: "Juicy mango popsicle with a citrus twist.",
        price: 2.49,
        imageUrl: "/images/brownie.png",
        rating: 4.5,
        category: "Popsicles",
        available: true,
    },
    {
        id: 10,
        name: "Berry Frost Popsicle",
        description: "Mixed berry popsicle with a frosty finish.",
        price: 2.59,
        imageUrl: "/images/brownie.png",
        rating: 4.4,
        category: "Popsicles",
        available: true,
    },
    {
        id: 11,
        name: "Chocolate Brownie Sundae",
        description: "Rich chocolate ice cream with chunks of brownie.",
        price: 5.49,
        imageUrl: "/images/brownie.png",
        rating: 4.9,
        category: "Sundaes",
        available: true,
    },
    {
        id: 12,
        name: "Caramel Crunch Sundae",
        description: "Vanilla ice cream with caramel and crunchy nuts.",
        price: 5.69,
        imageUrl: "/images/brownie.png",
        rating: 4.9,
        category: "Sundaes",
        available: true,
    },
];
