import type { Metadata } from "next";
import { Archivo, Berkshire_Swash } from "next/font/google";
import "./globals.css";

import { CartProvider } from "./_context/CartContext";
import { CountryProvider } from "./_context/CountryContext";
import { AuthProvider } from "./_context/AuthContext";
import React from "react";
import {ToastContainer} from "@/components/ui/use-toast";

// Fonts
const berkshireSwash = Berkshire_Swash({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-berkshire",
});

const archivo = Archivo({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-archivo",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${archivo.variable} ${berkshireSwash.variable} antialiased`}
        >
        {/* AUTH → COUNTRY → CART PROVIDERS */}
        <AuthProvider>
            <CountryProvider>
                <CartProvider>{children}</CartProvider>
            </CountryProvider>
            <ToastContainer />
        </AuthProvider>
        </body>
        </html>
    );
}
